repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
      - id: pylint
        additional_dependencies: [pylint, pandas, pytest, requests, bs4, tinkoff-investments, bestconfig]
        args: ['--disable=C0301,W0221, W0201, W0718, R0902, C0121']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
